version: '3.8'

services:
  web:
    build: .
    ports:
      - "127.0.0.1:5002:8000"
    env_file:
      - .env
    volumes:
      - ./app:/code/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - waro-network
    restart: unless-stopped

networks:
  waro-network:
    external: true
